# Introduction to Python

## Numpy

Numpy allows us to rapidly carry out operations over entire collection of values (it is impossible to divide one list by another, however you CAN do it with numpy)

In [1]:
## Numpy allows to perform calculations over entire arrays
import numpy as np

height = [1.73, 1.68, 1.71, 1.79]
np_height = np.array(height)
#numpy array takes list as an input

weight = [64.5, 88.4, 68.7, 59.2]
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
bmi

array([21.55100404, 31.32086168, 23.49440854, 18.47632721])

Remember that numpy can only contain values of a single type 


https://github.com/andrewch28/DataCamp

In [2]:
bmi > 23 # This will return a boolean array

#If we want to subset bmi array to only those elements, which are higher than 23:
bmi[bmi>23]

array([31.32086168, 23.49440854])

In [3]:
#shape attribute

np_2d = np.array([[64.5, 88.4, 68.7, 59.2],
                   [1.73, 1.68, 1.71, 1.79]])
np_2d.shape

(2, 4)

In [4]:
print(np_2d[0, 2])
np_2d[:, 1:3]

68.7


array([[88.4 , 68.7 ],
       [ 1.68,  1.71]])

In [5]:
print(np.mean(np_2d[0]))
print(np.median(np_2d[0]))

print(np.corrcoef(np_2d[0], np_2d[1]))
print(np.std(np_2d[0]))

print(np.sum(np_2d[0]))
print(np.sort(np_2d[0]))

70.2
66.6
[[ 1.         -0.86725192]
 [-0.86725192  1.        ]]
11.033811671403496
280.8
[59.2 64.5 68.7 88.4]


In [ ]:
# Convert positions and heights to numpy arrays: np_positions, np_heights
positions = ["GK", ...]
heights = [...]

np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == "GK"]

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != "GK"]