In [1]:
print("hello")

hello


In [12]:
import pandas as pd 
import numpy as np

food = pd.read_csv("databases/food.csv", index_col=0)

In [9]:
food.dtypes

Unnamed: 0         int64
country           object
food_category     object
consumption      float64
co2_emission     float64
dtype: object

In [13]:
food["length"] = food["food_category"].apply(len)
food.head()

country food_category  consumption  co2_emission  length
1  Argentina          pork        10.51         37.20       4
2  Argentina       poultry        38.66         41.53       7
3  Argentina          beef        55.48       1712.00       4
4  Argentina     lamb_goat         1.56         54.63       9
5  Argentina          fish         4.36          6.96       4

In [14]:
import statistics
statistics.mode(food["country"])

'Argentina'

In [19]:
np.quantile(food["consumption"], np.linspace(0, 1, 10))

array([  0.        ,   0.55777778,   1.93      ,   4.16333333,
         7.00555556,  11.68666667,  18.79333333,  32.13      ,
        77.08111111, 430.76      ])

In [22]:
#75th

seventy_fifth = np.quantile(food["consumption"], 0.75)
twenty_fifth = np.quantile(food["consumption"], 0.25)

IQR = seventy_fifth - twenty_fifth

q1 = twenty_fifth - 1.5 * IQR
q3 = seventy_fifth + 1.5 * IQR

print(q1, q3)


-36.28625 66.78375


In [23]:
import pandas as pd 

brics = pd.read_csv("databases/brics.csv")

In [25]:
brics["country"].sample()

2    India
Name: country, dtype: object

In [29]:
np.random.seed(12)
brics[["country"]].sample(3, replace=True)

country
3   China
3   China
1  Russia

In [30]:
from scipy.stats import iqr
iqr(food["consumption"])

25.767500000000002

In [32]:
from scipy.stats import uniform

In [38]:
uniform.cdf(7, 0, 12)

1 - uniform.cdf(7, 0, 12)

print(uniform.cdf(7, 0, 12) - uniform.cdf(4, 0, 12))

0.25000000000000006


In [41]:
from scipy.stats import uniform 
uniform.rvs(0, 5, size=2)

array([4.56269417, 0.94938172])

In [48]:
from scipy.stats import binom
print(binom.rvs(1, 0.5, size=1))
print(binom.rvs(1, 0.5, size=8))
print(binom.rvs(8, 0.5, size=1))

[0]
[1 0 1 1 1 0 0 1]
[6]


In [61]:
binom.pmf(50, 100, 0.5)

0.07958923738717875

In [58]:
binom.cdf(7, 10, 0.5)

0.9453125

In [71]:
from scipy.stats import norm
norm.cdf(187, 161, 7) 

0.9998981107702193

In [72]:
1 - norm.cdf(154, 161, 7)

0.8413447460685429

In [81]:
norm.ppf(0.9999999, 161, 7)

194.2739701617196

In [82]:
norm.rvs(161, 7, size = 10)

array([148.80500301, 166.2892896 , 176.19654754, 163.74626923,
       169.60136125, 176.19555321, 164.1300237 , 165.16493634,
       166.23350765, 145.77490729])

In [86]:
from scipy.stats import poisson

poisson.pmf(4, 7)

0.09122619163734964

In [89]:
poisson.cdf(8, 7)

0.7290912677380824

In [7]:
import pandas as pd
import numpy as np
churn_df = pd.read_csv("databases/telecom_churn.csv")
X_new = np.array([[56.8, 17.5],
                  [24.4, 24.1],
                  [50.1, 10.9]])

In [12]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=15)
X = churn_df[["total_day_charge", "total_eve_charge"]].values
y = churn_df["churn"].values

In [20]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=21,
                                                    stratify=y) 

In [24]:
churn_df["churn"].value_counts(normalize=True)

churn
0    0.855086
1    0.144914
Name: proportion, dtype: float64

In [23]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(metrics.classification_report(predictions, y_test))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       930
           1       0.32      0.67      0.44        70

    accuracy                           0.88      1000
   macro avg       0.65      0.78      0.68      1000
weighted avg       0.93      0.88      0.90      1000

